# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170131_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='place',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
