# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170131_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AlterField(
            model_name='place',
            name='parametr',
            field=models.IntegerField(),
        ),
    ]
